AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Foci 2020 Match API"
Parameters:
  LambdaRoleArn:
    Type: String
  Database:
    Type: String
  UserPoolArn:
    Type: String
  Env:
    Type: String

Globals:
  Function:
    Handler: index.default
    Runtime: nodejs12.x
    Timeout: 10
    MemorySize: 512
    Tracing: Active
    Environment:
      Variables:
        DYNAMO_TABLE: !Ref Database

Resources:
  MatchApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub Foci2020-${Env}-Match
      StageName: match
      TracingEnabled: true
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref UserPoolArn
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"  
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'*'"
          ResponseTemplates:
            application/json: '{ "message": $context.error.messageString }'            
        MISSING_AUTHENTICATION_TOKEN:
          StatusCode: 404
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"  
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'*'"
          ResponseTemplates:
            application/json: '{ "message": $context.error.messageString }'

  CreateMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-Match-CreateMatch
      CodeUri: dist/api/create-match
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /v1/matches
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  UpdateMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-Match-UpdateMatch
      CodeUri: dist/api/update-match
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /v1/matches/{matchId}
            Method: PUT
            Auth:
              Authorizer: CognitoAuthorizer

  SetFinalScoreOfMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-Match-SetFinalScoreOfMatch
      CodeUri: dist/api/set-final-score-of-match
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /v1/matches/{matchId}
            Method: PATCH
            Auth:
              Authorizer: CognitoAuthorizer

  ListMatches:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-Match-ListMatches
      CodeUri: dist/api/list-matches
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /v1/matches
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  GetMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-Match-GetMatch
      CodeUri: dist/api/get-match
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /v1/matches/{matchId}
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  DeleteMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-Match-DeleteMatch
      CodeUri: dist/api/delete-match
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /v1/matches/{matchId}
            Method: DELETE
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  MatchApi:
    Description: "Foci 2020 Match API"
    Value: !Sub "${MatchApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}"
