version: 2.1
jobs:
  api_unit_test:     
    docker:
      - image: circleci/node:11.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restoring API dependencies from cache 
          key: api-dependencies-{{ checksum "api/package.json" }}

      - run: 
          name: Installing API dependencies
          command: cd api && npm install

      - save_cache:
          paths:
            - api/node_modules
          key: api-dependencies-{{ checksum "api/package.json" }}

      - run:
          name: Running API linter
          command: cd api && npm run lint

      - run:
          name: Running API unit tests
          command: cd api && npm run test

      - store_artifacts:
          path: api/coverage
          destination: coverage
      
      - run:
          name: Build API
          command: npm run build:api
        
      - persist_to_workspace:
          root: ~/
          paths:
            - repo/api/dist
  api_deploy:
    parameters:
      env:
        type: string
        default: ''
    docker: 
      - image: cibuilds/aws:1.16.1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - deploy: 
          name: AWS Package
          command: aws cloudformation package --template-file cloudformation.yaml --s3-bucket ${AWS_PACKAGES_S3} --output-template-file packaged.cloudformation.yaml
      - deploy:
          name: AWS Deploy
          command: aws cloudformation deploy --template-file packaged.cloudformation.yaml --stack-name foci2020-<<parameters.env>> --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --parameter-overrides Env=<<parameters.env>>
 
workflows:
  version: 2.1
  api: 
    jobs:
      - api_unit_test   
      - api_deploy:
          env: 'DEV'
          requires:
            - api_unit_test
          filters:
            branches:
              only: 
                - develop
      - api_deploy:
          env: 'UAT'
          requires:
            - api_unit_test
          filters:
            branches:
              only: 
                - release                