AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Env:
    Type: String

Resources:
  FociTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: documentType-id
          AttributeType: S
        - AttributeName: segment
          AttributeType: S
        - AttributeName: documentType
          AttributeType: S
        - AttributeName: tournamentId
          AttributeType: S
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: matchId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: orderingValue
          AttributeType: S
      KeySchema:
        - AttributeName: documentType-id
          KeyType: HASH
        - AttributeName: segment
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: indexByTournamentId
          KeySchema:
            - AttributeName: tournamentId
              KeyType: HASH
            - AttributeName: documentType
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - matchId
        - IndexName: indexByTeamId
          KeySchema:
            - AttributeName: teamId
              KeyType: HASH
            - AttributeName: documentType
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - matchId
        - IndexName: indexByMatchId
          KeySchema:
            - AttributeName: matchId
              KeyType: HASH
            - AttributeName: documentType
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: indexByUserId
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: documentType
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: indexByDocumentType
          KeySchema:
            - AttributeName: documentType
              KeyType: HASH
            - AttributeName: orderingValue
              KeyType: RANGE
          Projection:
            ProjectionType: ALL                  

  FociLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Action:
            - sts:AssumeRole
          Principal:
            Service:
              - lambda.amazonaws.com
      Policies:
        - PolicyName: FociPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DeleteItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                  - sns:Publish
                  - xray:*
                Resource: '*'

  FociDeleteTeamTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub Foci2020-${Env}-DeleteTeamTopic

  FociDeleteTournamentTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub Foci2020-${Env}-DeleteTournamentTopic
  
  FociUpdateTeamTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub Foci2020-${Env}-UpdateTeamTopic

  FociUpdateTournamentTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub Foci2020-${Env}-UpdateTournamentTopic

Outputs:
  FociTableName:
    Value: !Ref FociTable
  FociLambdaRoleArn:
    Value: !GetAtt FociLambdaRole.Arn
  FociDeleteTeamTopic:
    Value: !Ref FociDeleteTeamTopic
  FociDeleteTournamentTopic:
    Value: !Ref FociDeleteTournamentTopic
  FociUpdateTeamTopic:
    Value: !Ref FociUpdateTeamTopic
  FociUpdateTournamentTopic:
    Value: !Ref FociUpdateTournamentTopic