AWSTemplateFormatVersion: '2010-09-09'

Resources:
  FociTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES 
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: documentType-id
          AttributeType: S
        - AttributeName: segment
          AttributeType: S
        - AttributeName: documentType
          AttributeType: S
        - AttributeName: tournamentId
          AttributeType: S
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: matchId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: orderingValue
          AttributeType: S
      KeySchema:
        - AttributeName: documentType-id
          KeyType: HASH
        - AttributeName: segment
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: indexByTournamentId
          KeySchema:
            - AttributeName: tournamentId
              KeyType: HASH
            - AttributeName: documentType
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - matchId
        - IndexName: indexByTeamId
          KeySchema:
            - AttributeName: teamId
              KeyType: HASH
            - AttributeName: documentType
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - matchId
        - IndexName: indexByMatchId
          KeySchema:
            - AttributeName: matchId
              KeyType: HASH
            - AttributeName: documentType
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: indexByUserId
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: documentType
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: indexByDocumentType
          KeySchema:
            - AttributeName: documentType
              KeyType: HASH
            - AttributeName: orderingValue
              KeyType: RANGE
          Projection:
            ProjectionType: ALL                  

  FociLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Action:
            - sts:AssumeRole
          Principal:
            Service:
              - lambda.amazonaws.com

  FociPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - FociLambdaRole
    Properties:
      PolicyName: FociPolicy
      Roles:
        - !Ref FociLambdaRole
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:DeleteItem
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:UpdateItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:DescribeStream
              - dynamodb:ListStreams
              - logs:DeleteSubscriptionFilter
              - logs:DeleteLogStream
              - logs:CreateExportTask
              - logs:DeleteResourcePolicy
              - logs:CreateLogStream
              - logs:DeleteMetricFilter
              - logs:TagLogGroup
              - logs:CancelExportTask
              - logs:DeleteRetentionPolicy
              - logs:DeleteLogDelivery
              - logs:AssociateKmsKey
              - logs:PutDestination
              - logs:DisassociateKmsKey
              - logs:UntagLogGroup
              - logs:DeleteLogGroup
              - logs:PutDestinationPolicy
              - logs:DeleteDestination
              - logs:PutLogEvents
              - logs:CreateLogGroup
              - logs:PutMetricFilter
              - logs:CreateLogDelivery
              - logs:PutResourcePolicy
              - logs:UpdateLogDelivery
              - logs:PutSubscriptionFilter
              - logs:PutRetentionPolicy
              - xray:*
            Resource: '*'
Outputs:
  FociTableName:
    Value: !Ref FociTable
  FociLambdaRoleArn:
    Value: !GetAtt FociLambdaRole.Arn
  FociTableStreamArn:
    Value: !GetAtt FociTable.StreamArn