AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Foci 2020 Match API'
Parameters: 
  LambdaRoleArn:
    Type: String
  Database:
    Type: String
  Env:
    Type: String

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Handler: index.default
    Runtime: nodejs12.x
    Timeout: 10
    MemorySize: 128
    Tracing: Active  
    Environment:
      Variables:
        DYNAMO_TABLE: !Ref Database

Resources:
  MatchApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub Foci2020-${Env}-Match
      StageName: Prod
      TracingEnabled: true
      GatewayResponses:
        MISSING_AUTHENTICATION_TOKEN:
          StatusCode: 404 
          ResponseTemplates:
            application/json: '{ "message": $context.error.messageString }'
     
  CreateMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-CreateMatch
      CodeUri: ./dist/create-match
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /match/v1/matches
            Method: POST   

  UpdateMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-UpdateMatch
      CodeUri: ./dist/update-match
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /match/v1/matches/{matchId}
            Method: PUT    

  ListMatches:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-ListMatches
      CodeUri: ./dist/list-matches
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /match/v1/matches
            Method: GET     

  GetMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-GetMatch
      CodeUri: ./dist/get-match
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /match/v1/matches/{matchId}
            Method: GET  

  DeleteMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-DeleteMatch
      CodeUri: ./dist/delete-match
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /match/v1/matches/{matchId}
            Method: DELETE  

Outputs:
  MatchApi:
    Description: "Foci 2020 Match API"
    Value: !Sub "${MatchApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}"