AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Foci 2020 Match API'
Parameters: 
  LambdaRoleArn:
    Type: String
  Database:
    Type: String
  TeamUpdatedTopic:
    Type: String    
  UpdateTeamOfMatchQueueArn:
    Type: String
  UpdateTeamOfMatchQueueUrl:
    Type: String
  TournamentUpdatedTopic:
    Type: String    
  UpdateTournamentOfMatchQueueArn:
    Type: String
  UpdateTournamentOfMatchQueueUrl:
    Type: String    
  Env:
    Type: String

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Handler: index.default
    Runtime: nodejs12.x
    Timeout: 10
    MemorySize: 512
    Tracing: Active  
    Environment:
      Variables:
        DYNAMO_TABLE: !Ref Database

Resources:
  MatchApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub Foci2020-${Env}-Match
      StageName: Prod
      TracingEnabled: true
      GatewayResponses:
        MISSING_AUTHENTICATION_TOKEN:
          StatusCode: 404 
          ResponseTemplates:
            application/json: '{ "message": $context.error.messageString }'
     
  CreateMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-CreateMatch
      CodeUri: ./dist/create-match
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /match/v1/matches
            Method: POST   

  UpdateMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-UpdateMatch
      CodeUri: ./dist/update-match
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /match/v1/matches/{matchId}
            Method: PUT    

  ListMatches:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-ListMatches
      CodeUri: ./dist/list-matches
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /match/v1/matches
            Method: GET     

  GetMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-GetMatch
      CodeUri: ./dist/get-match
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /match/v1/matches/{matchId}
            Method: GET  

  DeleteMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-DeleteMatch
      CodeUri: ./dist/delete-match
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref MatchApi
            Path: /match/v1/matches/{matchId}
            Method: DELETE  

  GetMatchesByHomeTeam:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-GetMatchesByHomeTeam
      CodeUri: ./dist/get-matches-by-home-team
      Role: !Ref LambdaRoleArn
      Environment:
        Variables:
          UPDATE_TEAM_OF_MATCH_QUEUE: !Ref UpdateTeamOfMatchQueueUrl
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref TeamUpdatedTopic            

  GetMatchesByAwayTeam:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-GetMatchesByAwayTeam
      CodeUri: ./dist/get-matches-by-away-team
      Role: !Ref LambdaRoleArn
      Environment:
        Variables:
          UPDATE_TEAM_OF_MATCH_QUEUE: !Ref UpdateTeamOfMatchQueueUrl      
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref TeamUpdatedTopic    

  UpdateTeamOfMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-UpdateTeamOfMatch
      CodeUri: ./dist/update-team-of-match
      Role: !Ref LambdaRoleArn
      Events:
        SQS:
          Type: SQS
          Properties:
            Queue: !Ref UpdateTeamOfMatchQueueArn        
            BatchSize: 1

  GetMatchesByTournament:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-GetMatchesByTournament
      CodeUri: ./dist/get-matches-by-tournament
      Role: !Ref LambdaRoleArn
      Environment:
        Variables:
          UPDATE_TOURNAMENT_OF_MATCH_QUEUE: !Ref UpdateTournamentOfMatchQueueUrl      
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref TournamentUpdatedTopic    

  UpdateTournamentOfMatch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Foci2020-${Env}-UpdateTournamentOfMatch
      CodeUri: ./dist/update-tournament-of-match
      Role: !Ref LambdaRoleArn
      Events:
        SQS:
          Type: SQS
          Properties:
            Queue: !Ref UpdateTournamentOfMatchQueueArn        
            BatchSize: 1            

Outputs:
  MatchApi:
    Description: "Foci 2020 Match API"
    Value: !Sub "${MatchApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}"