AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Foci 2020 API'
Parameters: 
  FociLambdaRoleArn:
    Type: String
  FociTableName:
    Type: String

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Environment:
      Variables:
        DYNAMO_TABLE: !Ref FociTableName

Resources:
  FociApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
     
  CreateTeam:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/create-team
      Handler: index.default
      Runtime: nodejs10.x
      Role: !Ref FociLambdaRoleArn
      Timeout: 10
      MemorySize: 512
      Tracing: Active
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref FociApi
            Path: /v1/teams
            Method: POST

  CreateTournament:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/create-tournament
      Handler: index.default
      Runtime: nodejs10.x
      Role: !Ref FociLambdaRoleArn
      Timeout: 10
      MemorySize: 512
      Tracing: Active
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref FociApi
            Path: /v1/tournaments
            Method: POST    

  CreateMatch:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/create-match
      Handler: index.default
      Runtime: nodejs10.x
      Role: !Ref FociLambdaRoleArn
      Timeout: 10
      MemorySize: 512
      Tracing: Active
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref FociApi
            Path: /v1/matches
            Method: POST   

  ListMatches:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/list-matches
      Handler: index.default
      Runtime: nodejs10.x
      Role: !Ref FociLambdaRoleArn
      Timeout: 10
      MemorySize: 512
      Tracing: Active
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref FociApi
            Path: /v1/matches
            Method: GET                                    

Outputs:
  FociApi:
    Description: "Foci 2020 API"
    Value: !Sub "https://${FociApi}.execute-api.${AWS::Region}.amazonaws.com/${FociApi.Stage}/"